

[2Shape]
Meter=Shape
MeterStyle=Shape:S
Chain=986
[2Text]
Meter=String
Text=s
MeterStyle=Set.String:S | String:S

[3Shape]
Meter=Shape
MeterStyle=Shape:S
Chain=789
[3Text]
Meter=String
Text=3
MeterStyle=Set.String:S | String:S

[4Shape]
Meter=Shape
X=(20*[Set.S])
Y=(-5*[Set.S])R
MeterStyle=Shape:S
Chain=36951
[4Text]
Meter=String
Text=s
MeterStyle=Set.String:S | String:S

[5Shape]
Meter=Shape
MeterStyle=Shape:S
Chain=369
[5Text]
Meter=String
Text=3
MeterStyle=Set.String:S | String:S