[A1]
Meter=String
x=2R
y=(80+#Scroll#-50)
MeterStyle=RegularText | A
Text=#A1#
DynamicVariables=1
Group=ScrollUpdate
LeftMouseUpAction=[!SetVariable Index 1][!CommandMeasure Input2 "ExecuteBatch 1"]
[A2]
Meter=String
MeterStyle=RegularText | A
Text=#A2#
LeftMouseUpAction=[!SetVariable Index 2][!CommandMeasure Input2 "ExecuteBatch 2"]
[A3]
Meter=String
MeterStyle=RegularText | A
Text=#A3#
LeftMouseUpAction=[!SetVariable Index 3][!CommandMeasure Input2 "ExecuteBatch 2"]
[A4]
Meter=String
MeterStyle=RegularText | A
Text=#A4#
LeftMouseUpAction=[!SetVariable Index 4][!CommandMeasure Input2 "ExecuteBatch 2"]
[A5]
Meter=String
MeterStyle=RegularText | A
Text=#A5#
LeftMouseUpAction=[!SetVariable Index 5][!CommandMeasure Input2 "ExecuteBatch 2"]
[A6]
Meter=String
MeterStyle=RegularText | A
Text=#A6#
LeftMouseUpAction=[!SetVariable Index 6][!CommandMeasure Input2 "ExecuteBatch 2"]
[A7]
Meter=String
MeterStyle=RegularText | A
Text=#A7#
LeftMouseUpAction=[!SetVariable Index 7][!CommandMeasure Input2 "ExecuteBatch 2"]
[A8]
Meter=String
MeterStyle=RegularText | A
Text=#A8#
LeftMouseUpAction=[!SetVariable Index 8][!CommandMeasure Input2 "ExecuteBatch 2"]
[A9]
Meter=String
MeterStyle=RegularText | A
Text=#A9#
LeftMouseUpAction=[!SetVariable Index 9][!CommandMeasure Input2 "ExecuteBatch 2"]
[A10]
Meter=String
MeterStyle=RegularText | A
Text=#A10#
LeftMouseUpAction=[!SetVariable Index 10][!CommandMeasure Input2 "ExecuteBatch 2"]
[A11]
Meter=String
MeterStyle=RegularText | A
Text=#A11#
LeftMouseUpAction=[!SetVariable Index 11][!CommandMeasure Input2 "ExecuteBatch 2"]
[A12]
Meter=String
MeterStyle=RegularText | A
Text=#A12#
LeftMouseUpAction=[!SetVariable Index 12][!CommandMeasure Input2 "ExecuteBatch 2"]
[A13]
Meter=String
MeterStyle=RegularText | A
Text=#A13#
LeftMouseUpAction=[!SetVariable Index 13][!CommandMeasure Input2 "ExecuteBatch 2"]
[A14]
Meter=String
MeterStyle=RegularText | A
Text=#A14#
LeftMouseUpAction=[!SetVariable Index 14][!CommandMeasure Input2 "ExecuteBatch 2"]
[A15]
Meter=String
MeterStyle=RegularText | A
Text=#A15#
LeftMouseUpAction=[!SetVariable Index 15][!CommandMeasure Input2 "ExecuteBatch 2"]
[A16]
Meter=String
MeterStyle=RegularText | A
Text=#A16#
LeftMouseUpAction=[!SetVariable Index 16][!CommandMeasure Input2 "ExecuteBatch 2"]
[A17]
Meter=String
MeterStyle=RegularText | A
Text=#A17#
LeftMouseUpAction=[!SetVariable Index 17][!CommandMeasure Input2 "ExecuteBatch 2"]
[A18]
Meter=String
MeterStyle=RegularText | A
Text=#A18#
LeftMouseUpAction=[!SetVariable Index 18][!CommandMeasure Input2 "ExecuteBatch 2"]
[A19]
Meter=String
MeterStyle=RegularText | A
Text=#A19#
LeftMouseUpAction=[!SetVariable Index 19][!CommandMeasure Input2 "ExecuteBatch 2"]
[A20]
Meter=String
MeterStyle=RegularText | A
Text=#A20#
LeftMouseUpAction=[!SetVariable Index 20][!CommandMeasure Input2 "ExecuteBatch 2"]
[A21]
Meter=String
MeterStyle=RegularText | A
Text=#A21#
LeftMouseUpAction=[!SetVariable Index 21][!CommandMeasure Input2 "ExecuteBatch 2"]
[A22]
Meter=String
MeterStyle=RegularText | A
Text=#A22#
LeftMouseUpAction=[!SetVariable Index 22][!CommandMeasure Input2 "ExecuteBatch 2"]
[A23]
Meter=String
MeterStyle=RegularText | A
Text=#A23#
LeftMouseUpAction=[!SetVariable Index 23][!CommandMeasure Input2 "ExecuteBatch 2"]
[A24]
Meter=String
MeterStyle=RegularText | A
Text=#A24#
LeftMouseUpAction=[!SetVariable Index 24][!CommandMeasure Input2 "ExecuteBatch 2"]
[A25]
Meter=String
MeterStyle=RegularText | A
Text=#A25#
LeftMouseUpAction=[!SetVariable Index 25][!CommandMeasure Input2 "ExecuteBatch 2"]