

[C2]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern2#
LeftMouseUpAction=[!SetVariable Index 2][!WriteKeyValue Variables Index 2 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C3]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern3#
LeftMouseUpAction=[!SetVariable Index 3][!WriteKeyValue Variables Index 3 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C4]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern4#
LeftMouseUpAction=[!SetVariable Index 4][!WriteKeyValue Variables Index 4 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C5]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern5#
LeftMouseUpAction=[!SetVariable Index 5][!WriteKeyValue Variables Index 5 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C6]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern6#
LeftMouseUpAction=[!SetVariable Index 6][!WriteKeyValue Variables Index 6 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C7]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern7#
LeftMouseUpAction=[!SetVariable Index 7][!WriteKeyValue Variables Index 7 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C8]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern8#
LeftMouseUpAction=[!SetVariable Index 8][!WriteKeyValue Variables Index 8 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C9]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern9#
LeftMouseUpAction=[!SetVariable Index 9][!WriteKeyValue Variables Index 9 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C10]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern10#
LeftMouseUpAction=[!SetVariable Index 10][!WriteKeyValue Variables Index 10 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C11]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern11#
LeftMouseUpAction=[!SetVariable Index 11][!WriteKeyValue Variables Index 11 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C12]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern12#
LeftMouseUpAction=[!SetVariable Index 12][!WriteKeyValue Variables Index 12 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C13]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern13#
LeftMouseUpAction=[!SetVariable Index 13][!WriteKeyValue Variables Index 13 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C14]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern14#
LeftMouseUpAction=[!SetVariable Index 14][!WriteKeyValue Variables Index 14 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C15]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern15#
LeftMouseUpAction=[!SetVariable Index 15][!WriteKeyValue Variables Index 15 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C16]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern16#
LeftMouseUpAction=[!SetVariable Index 16][!WriteKeyValue Variables Index 16 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C17]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern17#
LeftMouseUpAction=[!SetVariable Index 17][!WriteKeyValue Variables Index 17 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

