[C1]
Meter=String
x=2R
y=(80+#Scroll#-50)
DynamicVariables=1
MeterStyle=RegularText | C
Text=#C1#
Group=ScrollUpdate
LeftMouseUpAction=[!SetVariable Index 1][!WriteKeyValue Variables Index 1 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C2]
Meter=String
MeterStyle=RegularText | C
Text=#C2#
LeftMouseUpAction=[!SetVariable Index 2][!WriteKeyValue Variables Index 2 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C3]
Meter=String
MeterStyle=RegularText | C
Text=#C3#
LeftMouseUpAction=[!SetVariable Index 3][!WriteKeyValue Variables Index 3 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C4]
Meter=String
MeterStyle=RegularText | C
Text=#C4#
LeftMouseUpAction=[!SetVariable Index 4][!WriteKeyValue Variables Index 4 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C5]
Meter=String
MeterStyle=RegularText | C
Text=#C5#
LeftMouseUpAction=[!SetVariable Index 5][!WriteKeyValue Variables Index 5 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C6]
Meter=String
MeterStyle=RegularText | C
Text=#C6#
LeftMouseUpAction=[!SetVariable Index 6][!WriteKeyValue Variables Index 6 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C7]
Meter=String
MeterStyle=RegularText | C
Text=#C7#
LeftMouseUpAction=[!SetVariable Index 7][!WriteKeyValue Variables Index 7 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C8]
Meter=String
MeterStyle=RegularText | C
Text=#C8#
LeftMouseUpAction=[!SetVariable Index 8][!WriteKeyValue Variables Index 8 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C9]
Meter=String
MeterStyle=RegularText | C
Text=#C9#
LeftMouseUpAction=[!SetVariable Index 9][!WriteKeyValue Variables Index 9 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C10]
Meter=String
MeterStyle=RegularText | C
Text=#C10#
LeftMouseUpAction=[!SetVariable Index 10][!WriteKeyValue Variables Index 10 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C11]
Meter=String
MeterStyle=RegularText | C
Text=#C11#
LeftMouseUpAction=[!SetVariable Index 11][!WriteKeyValue Variables Index 11 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C12]
Meter=String
MeterStyle=RegularText | C
Text=#C12#
LeftMouseUpAction=[!SetVariable Index 12][!WriteKeyValue Variables Index 12 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C13]
Meter=String
MeterStyle=RegularText | C
Text=#C13#
LeftMouseUpAction=[!SetVariable Index 13][!WriteKeyValue Variables Index 13 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C14]
Meter=String
MeterStyle=RegularText | C
Text=#C14#
LeftMouseUpAction=[!SetVariable Index 14][!WriteKeyValue Variables Index 14 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C15]
Meter=String
MeterStyle=RegularText | C
Text=#C15#
LeftMouseUpAction=[!SetVariable Index 15][!WriteKeyValue Variables Index 15 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C16]
Meter=String
MeterStyle=RegularText | C
Text=#C16#
LeftMouseUpAction=[!SetVariable Index 16][!WriteKeyValue Variables Index 16 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C17]
Meter=String
MeterStyle=RegularText | C
Text=#C17#
LeftMouseUpAction=[!SetVariable Index 17][!WriteKeyValue Variables Index 17 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C18]
Meter=String
MeterStyle=RegularText | C
Text=#C18#
LeftMouseUpAction=[!SetVariable Index 18][!WriteKeyValue Variables Index 18 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C19]
Meter=String
MeterStyle=RegularText | C
Text=#C19#
LeftMouseUpAction=[!SetVariable Index 19][!WriteKeyValue Variables Index 19 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C20]
Meter=String
MeterStyle=RegularText | C
Text=#C20#
LeftMouseUpAction=[!SetVariable Index 20][!WriteKeyValue Variables Index 20 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C21]
Meter=String
MeterStyle=RegularText | C
Text=#C21#
LeftMouseUpAction=[!SetVariable Index 21][!WriteKeyValue Variables Index 21 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C22]
Meter=String
MeterStyle=RegularText | C
Text=#C22#
LeftMouseUpAction=[!SetVariable Index 22][!WriteKeyValue Variables Index 22 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C23]
Meter=String
MeterStyle=RegularText | C
Text=#C23#
LeftMouseUpAction=[!SetVariable Index 23][!WriteKeyValue Variables Index 23 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C24]
Meter=String
MeterStyle=RegularText | C
Text=#C24#
LeftMouseUpAction=[!SetVariable Index 24][!WriteKeyValue Variables Index 24 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]
[C25]
Meter=String
MeterStyle=RegularText | C
Text=#C25#
LeftMouseUpAction=[!SetVariable Index 25][!WriteKeyValue Variables Index 25 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]