

[C2]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern2#
LeftMouseUpAction=[!SetVariable Index 2][!WriteKeyValue Variables Index 2 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C3]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern3#
LeftMouseUpAction=[!SetVariable Index 3][!WriteKeyValue Variables Index 3 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

[C4]
Meter=String
MeterStyle=RegularText | C
Text=#Pattern4#
LeftMouseUpAction=[!SetVariable Index 4][!WriteKeyValue Variables Index 4 "SetCombination.ini"][!ActivateConfig "Combilaunch\@Settings" "SetCombination.ini"]

