[F1]
Meter=String
x=2R
y=(80+#Scroll#-50)
MeterStyle=IconText | F
Text=[\xE838]
DynamicVariables=1
Group=ScrollUpdate
LeftMouseUpAction=[!SetVariable Index ""][!WriteKeyValue Variables Index "" "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]

[F2]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=[!SetVariable Index 2][!WriteKeyValue Variables Index 2 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]

[F3]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=[!SetVariable Index 3][!WriteKeyValue Variables Index 3 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]

[F4]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=[!SetVariable Index 4][!WriteKeyValue Variables Index 4 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]

[F5]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=[!SetVariable Index 5][!WriteKeyValue Variables Index 5 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]

[F6]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
[F7]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
[F8]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
[F9]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F10]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F11]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F12]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F13]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F14]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F15]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F16]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F17]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F18]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F19]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F20]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F21]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F22]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F23]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F24]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=
[F25]
Meter=String
MeterStyle=IconText | F
Text=[\xE838]
LeftMouseUpAction=