

[F2]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 2][!WriteKeyValue Variables Index 2 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F3]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 3][!WriteKeyValue Variables Index 3 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F4]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 4][!WriteKeyValue Variables Index 4 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F5]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 5][!WriteKeyValue Variables Index 5 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F6]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 6][!WriteKeyValue Variables Index 6 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F7]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 7][!WriteKeyValue Variables Index 7 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F8]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 8][!WriteKeyValue Variables Index 8 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F9]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 9][!WriteKeyValue Variables Index 9 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F10]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 10][!WriteKeyValue Variables Index 10 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F11]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 11][!WriteKeyValue Variables Index 11 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F12]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 12][!WriteKeyValue Variables Index 12 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F13]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 13][!WriteKeyValue Variables Index 13 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F14]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 14][!WriteKeyValue Variables Index 14 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F15]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 15][!WriteKeyValue Variables Index 15 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F16]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 16][!WriteKeyValue Variables Index 16 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F17]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 17][!WriteKeyValue Variables Index 17 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

