

[F2]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 2][!WriteKeyValue Variables Index 2 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F3]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 3][!WriteKeyValue Variables Index 3 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

[F4]
Meter=String
MeterStyle=IconText | F
LeftMouseUpAction=[!SetVariable Index 4][!WriteKeyValue Variables Index 4 "#ROOTCONFIGPATH#FileManager\File Folder.ini"][!ActivateConfig "Combilaunch\FileManager"]        

