[N1]
Meter=String
y=(80+#Scroll#-50)
MeterStyle=RegularText | N
Text=#n1#
DynamicVariables=1
Group=ScrollUpdate
LeftMouseUpAction=[!SetVariable Index 1][!CommandMeasure Input "ExecuteBatch 1"]
[N2]
Meter=String
MeterStyle=RegularText | N
Text=#n2#
LeftMouseUpAction=[!SetVariable Index 2][!CommandMeasure Input "ExecuteBatch 2"]
[N3]
Meter=String
MeterStyle=RegularText | N
Text=#n3#
LeftMouseUpAction=[!SetVariable Index 3][!CommandMeasure Input "ExecuteBatch 2"]
[N4]
Meter=String
MeterStyle=RegularText | N
Text=#n4#
LeftMouseUpAction=[!SetVariable Index 4][!CommandMeasure Input "ExecuteBatch 2"]
[N5]
Meter=String
MeterStyle=RegularText | N
Text=#n5#
LeftMouseUpAction=[!SetVariable Index 5][!CommandMeasure Input "ExecuteBatch 2"]
[N6]
Meter=String
MeterStyle=RegularText | N
Text=#n6#
LeftMouseUpAction=[!SetVariable Index 6][!CommandMeasure Input "ExecuteBatch 2"]
[N7]
Meter=String
MeterStyle=RegularText | N
Text=#n7#
LeftMouseUpAction=[!SetVariable Index 7][!CommandMeasure Input "ExecuteBatch 2"]
[N8]
Meter=String
MeterStyle=RegularText | N
Text=#n8#
LeftMouseUpAction=[!SetVariable Index 8][!CommandMeasure Input "ExecuteBatch 2"]
[N9]
Meter=String
MeterStyle=RegularText | N
Text=#n9#
LeftMouseUpAction=[!SetVariable Index 9][!CommandMeasure Input "ExecuteBatch 2"]
[N10]
Meter=String
MeterStyle=RegularText | N
Text=#n10#
LeftMouseUpAction=[!SetVariable Index 10][!CommandMeasure Input "ExecuteBatch 2"]
[N11]
Meter=String
MeterStyle=RegularText | N
Text=#n11#
LeftMouseUpAction=[!SetVariable Index 11][!CommandMeasure Input "ExecuteBatch 2"]
[N12]
Meter=String
MeterStyle=RegularText | N
Text=#n12#
LeftMouseUpAction=[!SetVariable Index 12][!CommandMeasure Input "ExecuteBatch 2"]
[N13]
Meter=String
MeterStyle=RegularText | N
Text=#n13#
LeftMouseUpAction=[!SetVariable Index 13][!CommandMeasure Input "ExecuteBatch 2"]
[N14]
Meter=String
MeterStyle=RegularText | N
Text=#n14#
LeftMouseUpAction=[!SetVariable Index 14][!CommandMeasure Input "ExecuteBatch 2"]
[N15]
Meter=String
MeterStyle=RegularText | N
Text=#n15#
LeftMouseUpAction=[!SetVariable Index 15][!CommandMeasure Input "ExecuteBatch 2"]
[N16]
Meter=String
MeterStyle=RegularText | N
Text=#n16#
LeftMouseUpAction=[!SetVariable Index 16][!CommandMeasure Input "ExecuteBatch 2"]
[N17]
Meter=String
MeterStyle=RegularText | N
Text=#n17#
LeftMouseUpAction=[!SetVariable Index 17][!CommandMeasure Input "ExecuteBatch 2"]
[N18]
Meter=String
MeterStyle=RegularText | N
Text=#n18#
LeftMouseUpAction=[!SetVariable Index 18][!CommandMeasure Input "ExecuteBatch 2"]
[N19]
Meter=String
MeterStyle=RegularText | N
Text=#n19#
LeftMouseUpAction=[!SetVariable Index 19][!CommandMeasure Input "ExecuteBatch 2"]
[N20]
Meter=String
MeterStyle=RegularText | N
Text=#n20#
LeftMouseUpAction=[!SetVariable Index 20][!CommandMeasure Input "ExecuteBatch 2"]
[N21]
Meter=String
MeterStyle=RegularText | N
Text=#n21#
LeftMouseUpAction=[!SetVariable Index 21][!CommandMeasure Input "ExecuteBatch 2"]
[N22]
Meter=String
MeterStyle=RegularText | N
Text=#n22#
LeftMouseUpAction=[!SetVariable Index 22][!CommandMeasure Input "ExecuteBatch 2"]
[N23]
Meter=String
MeterStyle=RegularText | N
Text=#n23#
LeftMouseUpAction=[!SetVariable Index 23][!CommandMeasure Input "ExecuteBatch 2"]
[N24]
Meter=String
MeterStyle=RegularText | N
Text=#n24#
LeftMouseUpAction=[!SetVariable Index 24][!CommandMeasure Input "ExecuteBatch 2"]
[N25]
Meter=String
MeterStyle=RegularText | N
Text=#n25#
LeftMouseUpAction=[!SetVariable Index 25][!CommandMeasure Input "ExecuteBatch 2"]