

[N2]
Meter=String
MeterStyle=RegularText | N
Text=#Name2#
LeftMouseUpAction=[!SetVariable Index 2][!CommandMeasure Input "ExecuteBatch 1"]

[N3]
Meter=String
MeterStyle=RegularText | N
Text=#Name3#
LeftMouseUpAction=[!SetVariable Index 3][!CommandMeasure Input "ExecuteBatch 1"]

[N4]
Meter=String
MeterStyle=RegularText | N
Text=#Name4#
LeftMouseUpAction=[!SetVariable Index 4][!CommandMeasure Input "ExecuteBatch 1"]

