

[N2]
Meter=String
MeterStyle=RegularText | N
Text=#Name2#
LeftMouseUpAction=[!SetVariable Index 2][!CommandMeasure Input "ExecuteBatch 2"]

[N3]
Meter=String
MeterStyle=RegularText | N
Text=#Name3#
LeftMouseUpAction=[!SetVariable Index 3][!CommandMeasure Input "ExecuteBatch 2"]

[N4]
Meter=String
MeterStyle=RegularText | N
Text=#Name4#
LeftMouseUpAction=[!SetVariable Index 4][!CommandMeasure Input "ExecuteBatch 2"]

[N5]
Meter=String
MeterStyle=RegularText | N
Text=#Name5#
LeftMouseUpAction=[!SetVariable Index 5][!CommandMeasure Input "ExecuteBatch 2"]

[N6]
Meter=String
MeterStyle=RegularText | N
Text=#Name6#
LeftMouseUpAction=[!SetVariable Index 6][!CommandMeasure Input "ExecuteBatch 2"]

[N7]
Meter=String
MeterStyle=RegularText | N
Text=#Name7#
LeftMouseUpAction=[!SetVariable Index 7][!CommandMeasure Input "ExecuteBatch 2"]

[N8]
Meter=String
MeterStyle=RegularText | N
Text=#Name8#
LeftMouseUpAction=[!SetVariable Index 8][!CommandMeasure Input "ExecuteBatch 2"]

[N9]
Meter=String
MeterStyle=RegularText | N
Text=#Name9#
LeftMouseUpAction=[!SetVariable Index 9][!CommandMeasure Input "ExecuteBatch 2"]

[N10]
Meter=String
MeterStyle=RegularText | N
Text=#Name10#
LeftMouseUpAction=[!SetVariable Index 10][!CommandMeasure Input "ExecuteBatch 2"]

[N11]
Meter=String
MeterStyle=RegularText | N
Text=#Name11#
LeftMouseUpAction=[!SetVariable Index 11][!CommandMeasure Input "ExecuteBatch 2"]

[N12]
Meter=String
MeterStyle=RegularText | N
Text=#Name12#
LeftMouseUpAction=[!SetVariable Index 12][!CommandMeasure Input "ExecuteBatch 2"]

[N13]
Meter=String
MeterStyle=RegularText | N
Text=#Name13#
LeftMouseUpAction=[!SetVariable Index 13][!CommandMeasure Input "ExecuteBatch 2"]

[N14]
Meter=String
MeterStyle=RegularText | N
Text=#Name14#
LeftMouseUpAction=[!SetVariable Index 14][!CommandMeasure Input "ExecuteBatch 2"]

[N15]
Meter=String
MeterStyle=RegularText | N
Text=#Name15#
LeftMouseUpAction=[!SetVariable Index 15][!CommandMeasure Input "ExecuteBatch 2"]

[N16]
Meter=String
MeterStyle=RegularText | N
Text=#Name16#
LeftMouseUpAction=[!SetVariable Index 16][!CommandMeasure Input "ExecuteBatch 2"]

[N17]
Meter=String
MeterStyle=RegularText | N
Text=#Name17#
LeftMouseUpAction=[!SetVariable Index 17][!CommandMeasure Input "ExecuteBatch 2"]

