

[X2]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 2][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

[X3]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 3][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

[X4]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 4][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

[X5]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 5][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

[X6]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 6][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

[X7]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 7][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

[X8]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 8][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

[X9]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 9][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

[X10]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 10][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

[X11]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 11][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

[X12]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 12][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

[X13]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 13][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

[X14]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 14][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

[X15]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 15][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

[X16]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 16][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

[X17]
Meter=String
MeterStyle=IconText | X
LeftMouseUpAction=[!SetVariable NumberOfIndices "([#NumberOfIndices]-1)"][!SetVariable DeleteIndex 17][!Delay 5][!WriteKeyValue Variables NumberOfIndices [#NumberOfIndices] "#@#Checks.inc"][!CommandMeasure CombiScript "Delete"]

