[X1]
Meter=String
x=2R
y=(80+#Scroll#-50)
MeterStyle=IconText | X
Text=[\xE711]
DynamicVariables=1
Group=ScrollUpdate
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X2]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction2" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction2" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch2" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch2" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X3]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction3" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction3" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch3" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch3" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X4]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction4" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction4" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch4" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch4" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X5]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction5" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction5" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch5" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch5" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X6]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction6" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction6" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch6" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch6" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X7]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction7" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction7" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch7" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch7" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X8]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction8" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction8" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch8" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch8" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X9]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction9" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction9" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch9" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch9" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X10]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction10" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction10" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch10" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch10" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X11]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction11" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction11" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch11" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch11" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X12]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction12" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction12" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch12" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch12" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X13]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction13" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction13" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch13" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch13" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X14]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction14" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction14" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch14" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch14" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X15]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction15" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction15" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch15" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch15" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X16]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction16" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction16" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch16" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch16" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X17]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction17" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction17" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch17" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch17" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X18]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction18" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction18" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch18" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch18" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X19]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction19" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction19" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch19" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch19" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X20]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction20" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction20" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch20" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch20" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X21]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction21" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction21" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch21" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch21" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X22]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction22" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction22" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch22" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch22" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X23]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction23" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction23" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch23" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch23" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X24]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction24" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction24" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch24" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch24" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]
[X25]
Meter=String
MeterStyle=IconText | X
Text=[\xE711]
LeftMouseUpAction=[!WriteKeyValue Name "IfMatchAction25" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatchAction25" "" #@#Checks.inc][!WriteKeyValue Launch "IfMatch25" "" #@#Checks.inc][!WriteKeyValue Name "IfMatch25" "" #@#Checks.inc][!ActivateConfig "Combilaunch\Main"][!DeactivateConfig "Combilaunch\Main"][!Refresh]